[package]
name = "rusty-blog"
version = "0.1.0"
authors = ["Sam Lyon <sam.c.lyon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
